# Generated by Django 2.1.1 on 2018-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_analizer', '0002_auto_20180920_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='documents',
            field=models.ManyToManyField(to='documents_analizer.Document'),
        ),
    ]
